### PR TITLE
v1.2.0

### PR DESCRIPTION
**Pull request by jjr840430**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@jjr840430 the tests are failing due to missing `libucl`. Could you help fix it? Thanks.

```
checking for ucl.h in /usr/local/ucl... no
checking for ucl.h in /usr/lib/ucl... no
checking for ucl.h in /usr/ucl... no
checking for ucl.h in /usr/pkg... no
checking for ucl.h in /usr/local... no
checking for ucl.h in /usr... no
checking whether compiling and linking against libucl works... no
configure: error: 
```

**Comment by ronaldtse** [comment]
@jjr840430 indeed. However, Linux doesn't have `libucl`?

**Comment by jjr840430** [comment]
@ronaldtse I didn't check with Linux version but Linux may support libucl too.
I will try to confirm and let you know shortly.

**Comment by ronaldtse** [comment]
@jjr840430 RHEL/CentOS does not have `libucl` in yum, so it will most likely need manual building. That's why I suggested this: https://github.com/riboseinc/libnereon/issues/21

**Comment by jjr840430** [comment]
@ronaldtse I just checked that `libucl` library is supported on Ubuntu.
But it's not supported on CentOS/RHEL, then I will try to add building system based on CMake.

**Comment by jjr840430** [comment]
@ribose-jeffreylau I will merge it after implemented [homebrew-libnereon](https://github.com/riboseinc/libnereon/pull/23)

**Pull request merged**
