### PR TITLE
Added test cases for Travis CI

### PR DESCRIPTION
**Pull request by jjr840430**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@jjr840430 could you help finish the tests soon? It's already been a while open and we really want to complete this. Thanks.

**Comment by jjr840430** [comment]
@ronaldtse sorry for the delay, I will finish it today.

**Comment by jjr840430** [comment]
Implemented #209

**Comment by ronaldtse** [comment]
Thank you @jjr840430 !

**Comment by ronaldtse** [comment]
@erikbor could you help review the tests when you have time? Thanks!

**Pull request merged**
