### PR TITLE
Added release-upload target to Makefile

### PR DESCRIPTION
**Pull request by jjr840430**
@ronaldtse I added `release-upload` target into Makefile.
To use this target, it needs to set `GITHUB_ACCESS_TOKEN` environment variable.

For example:

```
GITHUB_ACCESS_TOKEN=xxxxxxxxxx make release-upload
```
or
```
export GITHUB_ACCESS_TOKEN=xxxxxxxxxxx
make release-upload
```

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks. Does this script actually package+upload the release to GitHub?

**Comment by ronaldtse** [comment]
Also could you uppercase "ChangeLog.md" to "CHANGELOG.md"? Thanks.

**Comment by jjr840430** [comment]
@ronaldtse yes, it uploads release on `github`

**Comment by jjr840430** [comment]
Implemented #101

**Pull request merged**
